### ISSUE TITLE
No mention of Boost dependencies in README

### ISSUE THREAD

**Issue by dfego** [jeaye/jeayeson#17]
There's no mention of the Boost dependencies anywhere in the project that I could find, except for the include directives that unfortunately brought my program to a halt when I tried to use jeayeson. While it would be great to not have these dependencies (feature request?), these should at least be prominently documented. A lot of users won't have or want to deal with Boost, and others will at least need to know how to install is required by this project.

**Comment by jeaye** [comment]
I think, at one point, this was in the README; thanks for pointing out that it isn't anymore. Boost is currently used for three things, ranked in order of importance:

* UFT16 to UTF8 conversion (since `<codecvt>` isn't yet available on many distros using GCC)
* `boost::variant`
* `boost::is_any_of` for tokenizing

`boost::variant` is the backbone of jeayeson; it could be replaced with `std::variant` when C++17 comes along, but would otherwise require a manual implementation. jeayeson used to not use boost for UTF* conversions, but we ran into portability issues. When the major distros are all on GCC5, I think this can change.

With all of that explained, I agree that this should at least be documented clearly in the README.
